version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/abm_git_update_bot/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(ci-deps)"
