name: AWS Lambda function deploy workflow

on:
  workflow_dispatch:
  push:
    paths: ["src/**", "Cargo.toml"]

jobs:
  build-and-deploy:
    name: Build and deploy AWS Lambda function
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install Zig toolchain
        uses: korandoru/setup-zig@v1
        with:
          zig-version: 0.10.1

      - name: Install Cargo Lambda
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with:
          repo: cargo-lambda/cargo-lambda
          platform: linux
          arch: x86_64

      - name: Install Zlib dependency
        run: |
          sudo apt-get update 
          sudo apt-get -y install zlib1g-dev

      - name: Build Lambda function.
        run: cargo lambda build --release

      - name: Deploy Lambda function
        run: |
          printf "TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}\nTELEGRAM_GROUP_ID=${{ secrets.TELEGRAM_GROUP_ID }}\nWEBHOOK_GH_SECRET=${{ secrets.WEBHOOK_GH_SECRET }}\nRUST_LOG=info" > .env
          cargo lambda deploy --env-file .env
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
